name: Release candidate

on:
  push:
    branches:
      - release/*

jobs:
  # Build images and publish RCs to DockerHub
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Get tag from VERSION file
        id: meta
        run: |
          VERSION=$(cat VERSION)
          TAG=${VERSION}
          echo "::set-output name=tag::${TAG}"
      
      - name: Build and push images
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: meienberger/runtipi:rc-${{ steps.meta.outputs.TAG }}
          cache-from: type=registry,ref=meienberger/runtipi:buildcache
          cache-to: type=registry,ref=meienberger/runtipi:buildcache,mode=max


          
